receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

exporters:
  logging:
    logLevel: DEBUG
  prometheus:
    endpoint: "127.0.0.1:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [logging]